### ISSUE TITLE
Website link broken

### ISSUE THREAD

**Issue by VishnuSanal** [avinashkranjan/avinashkranjan#1]
@avinashkranjan The link to your website is broken [here](https://github.com/avinashkranjan/avinashkranjan/blob/master/README.md#L14)!

It points to [https://github.com/avinashkranjan/avinashkranjan/blob/master/avinashkranjan.github.io](https://github.com/avinashkranjan/avinashkranjan/blob/master/avinashkranjan.github.io) instead of [avinashkranjan.github.io](avinashkranjan.github.io)

**Comment by avinashkranjan** [comment]
@VishnuSanal Thank you for Pointing out the broken link will fix it ASAP
